# Generated by Django 4.2.6 on 2023-12-29 12:04

from django.db import migrations, models
import structured.fields
import tests.app.test_module.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('structured_data', structured.fields.StructuredJSONField(default=dict, schema=tests.app.test_module.models.TestSchema)),
            ],
        ),
    ]
