# Generated by Django 4.2.14 on 2024-11-16 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildModel1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_field', models.CharField(max_length=255)),
                ('child_field', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChildModel2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_field', models.CharField(max_length=255)),
                ('child_field', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
