# Generated by Django 4.2.14 on 2024-11-17 17:53

from django.db import migrations
import structured.fields
import tests.app.test_module.models


class Migration(migrations.Migration):

    dependencies = [
        ('test_module', '0002_childmodel1_childmodel2'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodel',
            name='structured_data_list',
            field=structured.fields.StructuredJSONField(default=list, schema=tests.app.test_module.models.TestSchema),
        ),
    ]
