# Generated by Django 4.2.6 on 2025-05-30 08:00

from django.db import migrations
import structured.fields
import tests.app.test_module.models


class Migration(migrations.Migration):

    dependencies = [
        ("test_module", "0003_testmodel_structured_data_list"),
    ]

    operations = [
        migrations.AddField(
            model_name="testmodel",
            name="structured_data_union",
            field=structured.fields.StructuredJSONField(
                default=tests.app.test_module.models.init_union_schema,
                schema=tests.app.test_module.models.UnionSchema,
            ),
        ),
    ]
