# Generated by Django 4.2.6 on 2025-06-27 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_module', '0004_testmodel_structured_data_union'),
    ]

    operations = [
        migrations.AddField(
            model_name='simplerelationmodel',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
