# Generated by Django 4.2.23 on 2025-07-28 07:29

from django.db import migrations
import structured.fields
import tests.app.test_module.models


class Migration(migrations.Migration):

    dependencies = [
        ('test_module', '0005_simplerelationmodel_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodel',
            name='structured_data_recursive',
            field=structured.fields.StructuredJSONField(default=dict, schema=tests.app.test_module.models.RecursiveOnModelSchema),
        ),
    ]
