# Generated by Django 6.0.1 on 2026-04-08 09:08

import structured.fields
import tests.app.test_module.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_module", "0006_testmodel_structured_data_recursive"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArticleModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "structured_data",
                    structured.fields.StructuredJSONField(
                        default=tests.app.test_module.models.init_article_schema,
                        schema=tests.app.test_module.models.ArticleSchema,
                    ),
                ),
            ],
        ),
    ]
