# Generated by Django 6.0.4 on 2026-06-11 12:30

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_module", "0008_bookmodel_country_tag_author"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomManagerModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            managers=[
                ("items", django.db.models.manager.Manager()),
            ],
        ),
    ]
