# Generated by Django 6.0.4 on 2026-06-11 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_module", "0009_custommanagermodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomPKModel",
            fields=[
                (
                    "code",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
    ]
