# Generated by Django 6.0.4 on 2026-06-15 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_module", "0010_custompkmodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="SearchDisplayModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("thumbnail", models.CharField(blank=True, default="", max_length=500)),
            ],
        ),
    ]
