# Generated by Django 5.2.4 on 2026-06-15 15:39

import structured.fields
import tests.app.test_module.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_module", "0011_searchdisplaymodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="PublishableBookModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_published", models.BooleanField(default=False)),
                ("title", models.CharField(max_length=255)),
                (
                    "structured_data",
                    structured.fields.StructuredJSONField(
                        default=tests.app.test_module.models.init_book_schema,
                        schema=tests.app.test_module.models.BookSchema,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
